# This compose file deploys both the frontend and payment service
services:
  payment:
    image: banditantony9/payment:latest
    container_name: payment
    pull_policy: always
    env_file:
      - path: ./backend/payments-svc/.env.prod
        required: true
    expose:
      - 3000
    environment:
      MONGODB_URL: mongodb://admin:password@mongodb:27017
      MONGODB_NAME: Toza
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    command: npm run dev
    depends_on:
      - mongodb
      - redis
    networks:
      - toza
    restart: always
    stdin_open: true
    tty: true

  worker:
    image: banditantony9/payment:latest
    container_name: worker
    pull_policy: always
    env_file:
      - path: ./backend/payments-svc/.env.prod
        required: true
    environment:
      MONGODB_URL: mongodb://admin:password@mongodb:27017
      MONGODB_NAME: Toza
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    command: npm run worker
    depends_on:
      - payment
    networks:
      - toza
    volumes:
      - ./backend/payments-svc/:/usr/src/app
    restart: always
    stdin_open: true
    tty: true

  frontend:
    image: banditantony9/tozafrontend:latest
    container_name: frontend
    pull_policy: always
    restart: always
    ports:
      - "80:80"
    networks:
      - toza
    depends_on:
      - payment
    stdin_open: true
    tty: true


  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    ports:
      - "6379:6379"
    networks:
      - toza
    volumes:
      - cache:/data
    stdin_open: true
    tty: true

  mongodb:
    restart: always
    image: mongo:4.4.18
    container_name: mongo-cont
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - toza
    volumes:
      - toza-data:/data/db
    stdin_open: true
    tty: true

volumes:
  toza-data:
    driver: local
  cache:
    driver: local

networks:
  toza:
    driver: bridge